# Generated by Django 5.1.3 on 2024-11-20 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('date_created_at', models.DateField(auto_now_add=True)),
                ('time_created_at', models.TimeField(auto_now_add=True)),
                ('date_updated_at', models.DateField(auto_now=True)),
                ('time_updated_at', models.TimeField(auto_now=True)),
                ('date_echeance', models.DateField()),
                ('heure_echeance', models.TimeField()),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ma_tache', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
